### ISSUE TITLE
Make simple changes to the website.

### ISSUE THREAD

**Issue by samjain2907** [samjain2907/Personal-Website#1]
Make simple changes to the website or even to the README.md file. It would be great for ablsolute newcomer looking for a project to work on. It is a very basic model website so you could bring any modifications to it and make a pull request.

**Comment by Ilivanilton** [comment]
@samjain2907 I can do?

**Comment by samjain2907** [comment]
> @samjain2907 I can do?

Yeah sure! You can directly make a pull request.

**Comment by venky012** [comment]
added zoom animation to the social icons
