### ISSUE TITLE
Redesign the website and make improvements. 

### ISSUE THREAD

**Issue by samjain2907** [samjain2907/Personal-Website#20]
Improve the original content in the website and make simple ui changes. You can add  a new feature as well . It is advisable only for beginners to work on this and get themselves introduced to the world of open source.

**Comment by vp431** [comment]
@samjain2907 Sir, I am newcomer to OpenSource and willing to contibute in it. Can i solve this issue ?

**Comment by samjain2907** [comment]
Yes you can work on it. Go ahead and make a pull request. Upload a screenshot with the pull request of the changes you have made.


> @samjain2907 Sir, I am newcomer to OpenSource and willing to contibute in it. Can i solve this issue ?

Feel free to make  pull request and do send a screenshot of the improvements you have made with  it .
