### ISSUE TITLE
Redesign the website giving a new look to it.

### ISSUE THREAD

**Issue by samjain2907** [samjain2907/Personal-Website#4]
Absolute newcomers who want to start with git and github can fork and clone the repository and start working on it. You can redesign the website and add some new features or functionalities to it.
Feel free to send a pull request along with a screenshot of the changes you have made. Its a great way to increase your pull request count and getting started with open source.

**Comment by HeartBeat1608** [comment]
@samjain2907 
I've forked the repo. Might be giving it a new look soon.

**Comment by samjain2907** [comment]
> @samjain2907
> I've forked the repo. Might be giving it a new look soon.

Good! Go ahead and implement some good features .If you wish you may add some libraries as well. Do attach a screenshot with the pull request.

**Comment by HeartBeat1608** [comment]
Hey @samjain2907 

I finished the new theme. I shifted to a Darker Mode for the Page and made little changes to the visible components to make them look better. Here is a ScreenShot of a part of the page. 
![Screenshot from 2019-10-17 00-14-31](https://user-images.githubusercontent.com/46963675/66948966-4c172000-f073-11e9-9482-824d31c32794.png)
